const ERROR_CODES = {
  ERR_SUCCESS: 0,
  ERR_INVALID_DATA_INPUT: 1,
  ERR_USER_NOT_EXIST: 2,
  ERR_VERIFICATION_FAILED: 3,
  ERR_INVALID_REQUEST: 4,
  ERR_INVALID_TOKEN: 5, // invalid token
  ERR_BAD_REQUEST: 6,
  ERR_CHEATING: 7, // user is cheating
  ERR_SERVER_MAINTANANCE: 8,
  ERR_REACH_MAX_REQUEST: 9,
  ERR_NOT_TIME_FOR_FARMING: 10,
  ERR_NOT_KYC: 11,
  ERR_EXCEPTION: 500,
};

const JOB_TYPE = {
  JOB: 'JOB',
  RECURRENCE: 'RECURRENCE',
};

const TIME_UNIT = {
  minus: 60,
  hour: 3600,
  day: 86400,
};

const TOKEN_QR_CODE_EXPIRE_TIME = '2d';

const TOKEN_EXPIRE_TIME = '2d';

const TOKEN_EXPIRE_TIME_TELE = '3650d';

module.exports = {
  ERROR_CODES,
  JOB_TYPE,
  TIME_UNIT,
  TOKEN_QR_CODE_EXPIRE_TIME,
  TOKEN_EXPIRE_TIME,
  TOKEN_EXPIRE_TIME_TELE,
};
